### ISSUE TITLE
Issue after install?

### ISSUE THREAD

**Issue by gitihobo** [GeorgLegato/stable-diffusion-webui-vectorstudio#11]
Do I have to change or install something more aside from the github? I get this error Exception: TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)
Time taken: 3.30sTorch active/reserved: 3333/3786 MiB, Sys VRAM: 6180/8192 MiB (75.44%)

**Comment by GeorgLegato** [comment]
you need to download or install POTRACE to your system. the extension expect in its own folder a bin-folder where the POTRACE.exe is located

**Comment by gitihobo** [comment]
Perfect, one final question, how do I make it so my images get a transparent background, it seems to be inverted

**Comment by GeorgLegato** [comment]
by Image you means svg? some areas can be filled, because they are closed path. others not. so it seems you have non-transparency.
Try the Button "Cycle BG" to change background of SVG graphics, then you use on black what is white or transparent, if not wantedm use white backgrund and looks normal.
then select your svg and "Edit SVG" and check details. or use your fav svg editor
